//! Well-known note script roots.
//! This file was generated by build.rs.

/// Script root of the P2ID note script
pub const P2ID: &str = "0x02b82f685d19d8c0f11c1db33f0b4ae21b2c404010c6ea5292fb6980e5147759";

/// Script root of the P2IDR note script
pub const P2IDR: &str = "0x657411c1353ca16641ae56faedd67d7c1751e0751134e38c4dcf33ab8fae8aa1";

/// Script root of the SWAP note script
pub const SWAP: &str = "0x60a0ddbf22b315ad846505c496eb40f5edd1bcb32dd0827b8a062793c6fe14e3";
