//! Well-known note script roots.
//! This file was generated by build.rs.

/// Script root of the P2ID note script.
pub const P2ID: &str = "0x56ab74fa46300f5988caad8aefd0e105f7244f5784488b293be3509b251d4dfe";

/// Script root of the P2IDR note script.
pub const P2IDR: &str = "0xb36ea4df8d5fa29f2aa582931595b9171df0866d099c5df34868af0d6a60fad1";

/// Script root of the SWAP note script.
pub const SWAP: &str = "0x1c4dd8b76fac02a3c29d8c4b41f5f1717c9c96d59a28bda3545ca5c9b6f234ea";
