//! Well-known note script roots.
//! This file was generated by build.rs.

/// Script root of the P2ID note script
pub const P2ID: &str = "0x397b134e1426f19d662d5a33a1685d41a3a8fd283ce3ee637969694b2b5f60f1";

/// Script root of the P2IDR note script
pub const P2IDR: &str = "0x657b6f15ceeededbe918c8ca9da2b48edb49b9fd0eece4c634d4543048dafe13";

/// Script root of the SWAP note script
pub const SWAP: &str = "0x2dd51369a7fb33504bb952880eac672db945eeac4c5a146c0dafc79c7d03be6a";
