//! Well-known procedure roots.
//! This file was generated by build.rs.

/// Procedure root of the `RpoFalcon512` authentication component.
pub const RPO_FALCON_512_AUTH: &str =
    "0xeeb0e9d18708ce86a32954c4855bd0304bbc5f71a6170c80e63b76fcdefd2481";
