//! Well-known procedure roots.
//! This file was generated by build.rs.

/// Procedure root of the `RpoFalcon512` authentication component.
pub const RPO_FALCON_512_AUTH: &str =
    "0x9fa637ab3da3344894805adaec1014b07d3f8f3887be4a6d0216f4ec05264291";
