import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function AppLayout({ children }: {children: React.ReactNode}) {
  <div style={{ display: 'flex' }}>
    <Sidebar />
    <main style={{ flexGrow: 1 }}>{children}</main>
  </div>
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{
      <div style={{ display: 'flex' }}>
        <Sidebar />
        <main style={{ flexGrow: 1 }}>{children}</main>
      </div>
    }</body>
    </html>
  );
}
