//! Well-known note script roots.
//! This file was generated by build.rs.

/// Script root of the P2ID note script.
pub const P2ID: &str = "0xc7027378c923fb46912cd5406f75601268dce26a173b27a583b3492e6650c31a";

/// Script root of the P2IDR note script.
pub const P2IDR: &str = "0x4bce1c7dc2612c01d08bbeaf9bed42618d14114d05deba8f1f807c8598c4fb02";

/// Script root of the SWAP note script.
pub const SWAP: &str = "0xbb95b7a10443b75febbcd2d5f789f9720d9b237657cac8423b1b7debc97cf001";

/// Procedure root of the RpoFalcon512 authentication component.
pub const RPO_FALCON_512_AUTH_PROCEDURE: &str = "0xeeb0e9d18708ce86a32954c4855bd0304bbc5f71a6170c80e63b76fcdefd2481";
